import type { Activity, LatLng } from "@/types";

/**
 * 种子数据：默认围绕「上海·五角场/大学路」高校区约 3 公里范围。
 * 换成你自己的大学：改 SEED_CENTER，并把下面每个场馆的坐标平移过去即可。
 * 坐标为 GCJ-02（高德坐标系）。
 */
export const SEED_CENTER: LatLng = { lat: 31.3002, lng: 121.5132 };

type SeedVenue = Omit<Activity, "id">;

export const SEED_VENUES: SeedVenue[] = [
  // —— 一人食 ——
  {
    name: "深夜食堂 · 一个人的小面",
    category: "一人食",
    tags: ["一人食", "不喝酒", "平价", "快节奏"],
    lat: 31.3015,
    lng: 121.5138,
    address: "五角场 淞沪路 234 号",
    costMin: 25,
    costMax: 45,
    durationMin: 60,
    openTime: "11:00",
    closeTime: "23:30",
    rating: 4.5,
    indoor: true,
    alcoholFree: true,
    socialScore: 30,
    description: "吧台座为主，一个人也坐得自在。",
  },
  {
    name: "回转寿司 · 独享位",
    category: "一人食",
    tags: ["一人食", "日料", "无社交压力"],
    lat: 31.303,
    lng: 121.516,
    address: "大学路 88 号",
    costMin: 60,
    costMax: 90,
    durationMin: 60,
    openTime: "11:00",
    closeTime: "22:00",
    rating: 4.2,
    indoor: true,
    alcoholFree: false,
    socialScore: 50,
    description: "回转带上随手取，无需等位聊天。",
  },
  {
    name: "单人小火锅 · 独享锅",
    category: "一人食",
    tags: ["一人食", "火锅", "不尴尬"],
    lat: 31.299,
    lng: 121.515,
    address: "政通路 102 号",
    costMin: 50,
    costMax: 80,
    durationMin: 75,
    openTime: "11:00",
    closeTime: "23:00",
    rating: 4.4,
    indoor: true,
    alcoholFree: false,
    socialScore: 40,
    description: "一人一锅，隔板设计，一个人吃火锅不尴尬。",
  },

  // —— 脱口秀 ——
  {
    name: "大笑脱口秀俱乐部",
    category: "脱口秀",
    tags: ["脱口秀", "夜间", "社交友好", "有趣"],
    lat: 31.304,
    lng: 121.514,
    address: "五角场万达广场 B1",
    costMin: 80,
    costMax: 120,
    durationMin: 90,
    openTime: "19:30",
    closeTime: "22:30",
    rating: 4.6,
    indoor: true,
    alcoholFree: true,
    socialScore: 85,
    description: "晚场开放麦，观众互动多，容易认识同好。",
  },
  {
    name: "开放麦 · 周六夜现场",
    category: "脱口秀",
    tags: ["脱口秀", "开放麦", "社交", "夜间"],
    lat: 31.305,
    lng: 121.517,
    address: "大学路 16 号 3F",
    costMin: 50,
    costMax: 80,
    durationMin: 90,
    openTime: "19:00",
    closeTime: "23:00",
    rating: 4.3,
    indoor: true,
    alcoholFree: false,
    socialScore: 90,
    description: "新人开放麦，气氛轻松，散场常有人约宵夜。",
  },

  // —— 书店 ——
  {
    name: "24 小时不打烊书店",
    category: "书店",
    tags: ["书店", "安静", "独处", "文艺", "夜间"],
    lat: 31.302,
    lng: 121.512,
    address: "淞沪路 170 号",
    costMin: 0,
    costMax: 40,
    durationMin: 60,
    openTime: "00:00",
    closeTime: "24:00",
    rating: 4.5,
    indoor: true,
    alcoholFree: true,
    socialScore: 20,
    description: "深夜也能坐下来看书，收尾行程的绝佳选择。",
  },
  {
    name: "复旦经世书局",
    category: "书店",
    tags: ["书店", "校园", "文艺", "安静"],
    lat: 31.2955,
    lng: 121.4995,
    address: "邯郸路 220 号（复旦校内）",
    costMin: 0,
    costMax: 50,
    durationMin: 45,
    openTime: "09:00",
    closeTime: "21:00",
    rating: 4.6,
    indoor: true,
    alcoholFree: true,
    socialScore: 15,
    description: "校园书店，买本书慢慢翻，独处首选。",
  },

  // —— 桌游 ——
  {
    name: "狼人杀桌游吧",
    category: "桌游",
    tags: ["桌游", "社交", "组队", "有趣"],
    lat: 31.3035,
    lng: 121.5155,
    address: "大学路 42 号 2F",
    costMin: 40,
    costMax: 70,
    durationMin: 120,
    openTime: "13:00",
    closeTime: "23:00",
    rating: 4.4,
    indoor: true,
    alcoholFree: true,
    socialScore: 95,
    description: "现场拼桌，一局狼人杀就能认识一桌人。",
  },
  {
    name: "推理剧本杀 · 解谜馆",
    category: "桌游",
    tags: ["桌游", "剧本杀", "社交", "组队"],
    lat: 31.3005,
    lng: 121.5165,
    address: "国定路 333 号",
    costMin: 100,
    costMax: 150,
    durationMin: 150,
    openTime: "14:00",
    closeTime: "24:00",
    rating: 4.5,
    indoor: true,
    alcoholFree: false,
    socialScore: 90,
    description: "6-8 人本，DM 会帮你拼队友。",
  },

  // —— 羽毛球 ——
  {
    name: "江湾体育场羽毛球馆",
    category: "羽毛球",
    tags: ["羽毛球", "运动", "组队", "健康"],
    lat: 31.306,
    lng: 121.52,
    address: "国和路 346 号",
    costMin: 40,
    costMax: 80,
    durationMin: 90,
    openTime: "08:00",
    closeTime: "22:00",
    rating: 4.3,
    indoor: true,
    alcoholFree: true,
    socialScore: 85,
    description: "找搭子拼场，双打缺一人常有。",
  },
  {
    name: "复旦体育馆羽毛球场",
    category: "羽毛球",
    tags: ["羽毛球", "运动", "校园", "平价"],
    lat: 31.295,
    lng: 121.4995,
    address: "邯郸路 220 号（复旦校内）",
    costMin: 20,
    costMax: 50,
    durationMin: 90,
    openTime: "09:00",
    closeTime: "21:00",
    rating: 4.1,
    indoor: true,
    alcoholFree: true,
    socialScore: 80,
    description: "校园价，学生多，容易凑到搭子。",
  },

  // —— 徒步 ——
  {
    name: "新江湾城湿地绿道徒步",
    category: "徒步",
    tags: ["徒步", "户外", "自然", "免费", "健康"],
    lat: 31.325,
    lng: 121.521,
    address: "新江湾城生态绿道",
    costMin: 0,
    costMax: 0,
    durationMin: 120,
    openTime: "06:00",
    closeTime: "21:00",
    rating: 4.4,
    indoor: false,
    alcoholFree: true,
    socialScore: 60,
    description: "城市湿地绿道，一个人走也很舒服。",
  },
  {
    name: "复旦校园夜行漫步",
    category: "徒步",
    tags: ["徒步", "校园", "夜间", "安静"],
    lat: 31.2952,
    lng: 121.4985,
    address: "复旦大学邯郸校区",
    costMin: 0,
    costMax: 0,
    durationMin: 60,
    openTime: "06:00",
    closeTime: "23:00",
    rating: 4.3,
    indoor: false,
    alcoholFree: true,
    socialScore: 40,
    description: "校园夜走，安静又安全，消食好去处。",
  },

  // —— 探店 ——
  {
    name: "大学路猫咖探店",
    category: "探店",
    tags: ["探店", "咖啡", "猫", "文艺"],
    lat: 31.3015,
    lng: 121.517,
    address: "大学路 59 号",
    costMin: 30,
    costMax: 60,
    durationMin: 60,
    openTime: "10:00",
    closeTime: "22:00",
    rating: 4.5,
    indoor: true,
    alcoholFree: true,
    socialScore: 55,
    description: "撸猫 + 咖啡，一个人也不会无聊。",
  },
  {
    name: "合生汇美食探店",
    category: "探店",
    tags: ["探店", "美食", "商场"],
    lat: 31.308,
    lng: 121.516,
    address: "五角场合生汇 5F",
    costMin: 50,
    costMax: 100,
    durationMin: 90,
    openTime: "10:00",
    closeTime: "22:00",
    rating: 4.2,
    indoor: true,
    alcoholFree: false,
    socialScore: 60,
    description: "逛吃一体，一个人也能吃出花样。",
  },

  // —— 看展 ——
  {
    name: "五角场现代美术馆",
    category: "看展",
    tags: ["看展", "文艺", "艺术", "安静"],
    lat: 31.3035,
    lng: 121.5135,
    address: "政立路 98 号",
    costMin: 30,
    costMax: 80,
    durationMin: 90,
    openTime: "10:00",
    closeTime: "18:00",
    rating: 4.4,
    indoor: true,
    alcoholFree: true,
    socialScore: 45,
    description: "当代艺术常设展，下午场最佳。",
  },
  {
    name: "大学路艺术空间 · 限时展",
    category: "看展",
    tags: ["看展", "艺术", "文艺", "免费"],
    lat: 31.3018,
    lng: 121.5165,
    address: "大学路 7 号",
    costMin: 0,
    costMax: 50,
    durationMin: 60,
    openTime: "10:00",
    closeTime: "20:00",
    rating: 4.1,
    indoor: true,
    alcoholFree: true,
    socialScore: 50,
    description: "年轻艺术家限时展，免费为主。",
  },
];
